### ISSUE TITLE
設計書をちゃんと書いてみる

### ISSUE THREAD

**Issue by mihoijuin** [mihoijuin/wp_nandedemodakara#33]
#### TODO
- [x] 一枚（TOPページ）設計書書く
- [x] これで間違ってないか確認
- [x] 他のページも書く
  - [x] 記事一覧ページ（index.html)
  - [x] 管理人ページ (profile.html)
  - [x] 記事ページ (page.html)
- [x] 最終チェック

#### Discription
デザインはそのただ作りたい！が一人歩きしてしまうので、完璧なコードがないんですよ。
簡単に変えれちゃいますし、デザインの良し悪しは時代ですぐに変わりますから。。。

なので、大規模プロジェクトでちゃんとやるときは、作る前にしっかりルールを決めて、柔軟に対応出来るように設計します。
```
・何種類画面あって
・それぞれの画面にどんな要素があって
・こことここは同じレイアウト
・この画面では変える
```

手書きでも設計書です。
デザインのときはモックアップとか言われますかね。
レビューを頼むときとかは必要ですね。
簡単なやつでいいです。
ルールやこの先何を想定してるのかを把握するために。
指標が無ければ、レビューのしようが無いです。
特にcssは作る画面や考え方によって正解が変わるので。

設計書はあんまり外に出回らないので。。。
https://www.ec-cube.net/download/document.php
オープンソースで設計書を見せてるプロジェクトがありますが、デザインはわかりません。

設計書は画面のイメージがあればそれでいいです。
絵で、四角がいっぱい並んだだけのもので問題ないですよ。
コミュニケーションを取るためだけのものなので。
